### ISSUE TITLE
Rotating timer like Pomo? 

### ISSUE THREAD

**Issue by suedeyoung** [vitorgalvao/shrieking-chimes-workflow#1]
I recently got a new laptop at work and noticed that the timer for the old sandwich timer was not showing in the menu, so I found this one. 

Before I download, will this have any functionality to do 20 minutes of work, take a 5-minute break, and rotate as the Pomo/Sandwich timer did? 

Always good to see your stuff, and I can't wait to see what this will grow into!

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

No current plans to add the pomodoro functionality directly in this one because it’s using a different solution (Ventura’s Clock app). But the workflow does have [External Triggers](https://www.alfredapp.com/help/workflows/triggers/external/) which [allows you to set that up](https://www.alfredforum.com/topic/11518-sandwichtimer-—-run-pomodoros-and-other-timers/page/2/#comment-103848).
